import "../globals.css";
import type { Metadata } from "next";
import { getMessages } from "next-intl/server";
import {NextIntlClientProvider} from 'next-intl';
import { Header } from "@/components/layouts/Header";
import { Foooter } from "@/components/layouts/Footer";
import { Geist, Geist_Mono, Oswald, Pacifico } from "next/font/google";
import { PreHedear } from "@/components/layouts/PreHeader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Mbokaservices",
  description: "Generated by create next app",
};


export default async function LayoutLocal({ children }: {children: React.ReactNode}) {

  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <div className={`${geistSans.variable} ${pacifico.variable} ${geistMono.variable} ${oswald.variable} h-full antialiased`}>
        <PreHedear />
        <Header />
        <main>
          {children}
        </main>
        <Foooter />
      </div>
    </NextIntlClientProvider>
  );
}
