import "./globals.css";
import type { Metadata } from "next";
import { Header } from "@/components/layouts/Header";
import { Foooter } from "@/components/layouts/Footer";
import { Geist, Geist_Mono, Oswald } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mboka services",
  description: "Generated by create next app",
};



export default function LayoutLocal({ children }: LayoutProps<"/">) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} h-full antialiased`}>
      <Header />
      <main>
        {children}
      </main>
      <Foooter />
    </div>
  );
}
